services:
  fastapi:
    build: .
    container_name: user-microservice-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
