services:
  fastapi:
    build: .
    container_name: microservice-terraform-deploy-aws-gcp
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
